### ISSUE TITLE
interaction fail error

### ISSUE THREAD

**Issue by OnurGumus** [facebook/memlab#58] opened 2023-01-12 13:42 UTC
Hi, I am just follow the tutorial and even youtube one fails with below
```
page-load(baseline)[s1] > action-on-page(target)[s2] > revert(final)[s3]  
interaction fail, making 2 more attempt(s)...
interaction fail, making 1 more attempt(s)...
Use `memlab help` or `memlab <COMMAND> -h` to get helper text
interaction fail
onur@Onurs-MBP scenarios % 

```

Error seems cryptic and I don't understand what's wrong.

**Comment by JacksonGL** [comment] 2023-01-12 17:43
@OnurGumus Thanks for reporting this issue. Are you following this [tutorial](https://facebook.github.io/memlab/docs/getting-started#write-a-test-scenario)?

I couldn't reproduce the error. Which version of OS and memlab are you using? (please check memlab versions with the `memlab version` command)

Can you add the `--verbose` flag when running memlab and copy-and-paste the error message here? Thanks

**Comment by JacksonGL** [comment] 2023-01-16 22:21
> [console.error]: Failed to load resource: the server responded with a status of 403 ()

It seems like there was a problem connecting to YouTube when the page first loaded (403 means the server refused to authorize the request). Not sure why this happens. You can try running memlab on a different machine or internet connection. Turning off your VPN or proxy server (if any) might also help.

Additionally, you can run the scenario in "headful" mode by adding the flags `--debug --headful`. This will open Chromium and pause the memlab execution, allowing you to manually type in the YouTube url and check for any browser or network issues.

**Comment by JacksonGL** [comment] 2023-02-01 07:06
Closing as the error is not reproducible

**Closed by JacksonGL** 2023-02-01 07:06 UTC

**Comment by Ni55aN** [comment] 2023-07-20 09:44
The example from [the main page](https://facebook.github.io/memlab/) throws exactly the same error

```js
// test.js
function url() {
  return 'https://www.google.com/maps/';
}
async function action(page) {
  await page.click('button[aria-label="Hotels"]');
}
async function back(page) {
  await page.click('[aria-label="Clear search"]');
}

module.exports = {action, back, url};
```

**Comment by JacksonGL** [comment] 2023-07-20 16:27
@Ni55aN The reason for the error in that specific example is the UI element specified in the test scenario file can not be found in the page. I need to find a better example to showcase on the main page.

Try this test scenarios which pins to a location, let me know if this still doesn't work:

```
// test.js
function url() {
  return 'https://www.google.com/maps/place/Silicon+Valley,+CA/@37.4026892,-122.2059062,11z';
}
async function action(page) {
  await page.click('button[aria-label="Hotels"]');
}
async function back(page) {
  await page.click('[aria-label="Clear search"]');
}

module.exports = {action, back, url};
```

**Comment by Ni55aN** [comment] 2023-07-20 16:34
@JacksonGL yep, the examples from docs work fine
